# Generated by Django 4.2.6 on 2023-11-09 03:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "rg",
                    models.CharField(
                        max_length=11,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "telefone1",
                    models.CharField(
                        max_length=11,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "telefone2",
                    models.CharField(
                        max_length=11,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "endereco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.endereco",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdemDeServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket", models.CharField(max_length=200)),
                ("descricao", models.TextField(max_length=600)),
                ("previsao_chegada", models.DateTimeField()),
                ("previsao_execucao", models.DateTimeField()),
                (
                    "material",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "equipamento",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("contrato", models.CharField(blank=True, max_length=700, null=True)),
                (
                    "atividade",
                    models.CharField(
                        choices=[
                            ("Manutenção", "Manutenção"),
                            ("Ativação", "Ativação"),
                            ("Logística", "Logística"),
                            ("Teste Interno", "Teste Interno"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status_tecnico",
                    models.CharField(
                        choices=[
                            ("Aguardando Aceite", "Aguardando Aceite"),
                            ("À Caminho", "À Caminho"),
                            ("No Local", "No local"),
                            ("Finalizado", "Finalizado"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Aguardando", "Aguardando"),
                            ("Atenção", "Atenção"),
                            ("Urgente", "Urgente"),
                            ("Concluído", "Concluído"),
                        ],
                        default="Aguardando",
                        max_length=10,
                    ),
                ),
                (
                    "atraso_em_minutos",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Selecione"),
                            ("15", "15 minutos"),
                            ("30", "30 minutos"),
                            ("60", "1 hora"),
                            ("120", "2 horas"),
                            ("180", "3 horas"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "atraso_descricao",
                    models.TextField(blank=True, max_length=400, null=True),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="staff.cliente"
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordens_staff",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordens_técnico",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricoOsFinalizada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_finalizada", models.DateTimeField(auto_now_add=True)),
                ("nome_cliente", models.CharField(max_length=30)),
                ("rg_cliente", models.CharField(max_length=9)),
                ("observacoes", models.TextField(max_length=400)),
                ("foto", models.ImageField(upload_to="img/historico_os_finalizada/")),
                (
                    "ordem_de_servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_os",
                        to="staff.ordemdeservico",
                    ),
                ),
            ],
        ),
    ]
