# Generated by Django 4.2.6 on 2023-11-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemdeservico",
            name="atraso_descricao",
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="ordemdeservico",
            name="atraso_em_minutos",
            field=models.CharField(
                blank=True,
                choices=[
                    ("15", "15 minutos"),
                    ("30", "30 minutos"),
                    ("60", "1 hora"),
                    ("120", "2 horas"),
                    ("180", "3 horas"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
