# Generated by Django 4.2.6 on 2023-11-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0002_alter_cliente_rg_alter_cliente_telefone1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemdeservico",
            name="ticket",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
