# Generated by Django 4.2.6 on 2023-11-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0003_alter_ordemdeservico_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicoosfinalizada",
            name="rg_cliente",
            field=models.CharField(max_length=12),
        ),
    ]
