# Generated by Django 4.2.6 on 2023-11-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_ordemdeservico_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemdeservico',
            name='atraso_em_minutos',
            field=models.CharField(choices=[('', 'Selecione'), ('15', '15 minutos'), ('30', '30 minutos'), ('60', '1 hora'), ('120', '2 horas'), ('180', '3 horas')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='descricao_reagendamento',
            field=models.TextField(default=None, max_length=400),
        ),
    ]
