# Generated by Django 4.2.6 on 2023-11-09 04:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0004_alter_historicoosfinalizada_rg_cliente"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicoosfinalizada",
            old_name="nome_cliente",
            new_name="nome_responsavel",
        ),
        migrations.RenameField(
            model_name="historicoosfinalizada",
            old_name="rg_cliente",
            new_name="rg_responsavel",
        ),
    ]
