# Generated by Django 4.2.6 on 2023-11-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0005_alter_ordemdeservico_atraso_em_minutos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicoosfinalizada",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="videos/historico_os_finalizada/"
            ),
        ),
        migrations.AddField(
            model_name="ocorrencia",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="videos/ocorrencias/"
            ),
        ),
    ]
