# Generated by Django 4.2.6 on 2023-11-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_historicoosfinalizada_video_ocorrencia_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='aceite',
            field=models.BooleanField(default=False),
        ),
    ]
