# Generated by Django 4.2.6 on 2023-11-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_cliente_telefone1_alter_cliente_telefone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='descricao_reagendamento',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='reagendar',
            field=models.BooleanField(default=False),
        ),
    ]
