# Generated by Django 4.2.6 on 2023-11-11 00:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0008_ordemdeservico_vezes_reagendada_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordemdeservico",
            name="reagendar",
        ),
    ]
